### Задание 1

In [16]:
# Импортируйте библиотеку Numpy и дайте ей псевдоним np.

import numpy as np

In [17]:
#Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 
a = np.array([[1, 6],[2, 8],[3, 11], [3, 10],[1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [18]:
# найдите среднее значение по каждому признаку, используя метод mean массива Numpy. 
#Результат запишите в массив mean_a, в нем должно быть 2 элемента.
mean_a = a.mean(axis=0)
mean_a


array([2. , 8.4])

### Задание 2

In [21]:
# Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a.
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [26]:
# Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. 
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp


8.0

In [32]:
# поделите a_centered_sp на N-1, где N - число наблюдений
print (a_centered_sp / (a_centered.shape[0] - 1))

2.0
